package rentalmobil;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kevin
 */
import javax.swing.*;
import java.sql.*;

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setTitle("Aplikasi Rental Mobil");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFusername = new javax.swing.JTextField();
        TFpassword = new javax.swing.JPasswordField();
        Admin = new javax.swing.JLabel();
        BtnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TFusername.setBackground(new java.awt.Color(217, 217, 217));
        TFusername.setBorder(null);
        getContentPane().add(TFusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 330, 30));

        TFpassword.setBackground(new java.awt.Color(217, 217, 217));
        TFpassword.setBorder(null);
        getContentPane().add(TFpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 320, 30));

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Admin.png"))); // NOI18N
        Admin.setText("jLabel1");
        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        BtnAdmin.setText("Admin");
        BtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "select * from akun where username = '" + TFusername.getText()
                    + "' AND password = '" + TFpassword.getText() + "'AND role = 'admin'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
                String username = rs.getString("username");
                UserSession.setUsername(username);
                if(TFusername.getText().equals(rs.getString("username"))
                        && TFpassword.getText().equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Berhasil Login");
                    this.setVisible(false);
                    new MenuAdmin().setVisible(true);
                }
            }else {
                JOptionPane.showMessageDialog(null, "Username atau Password salah");
            }
        }catch (Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());    
        }
    }//GEN-LAST:event_BtnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton BtnAdmin;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JTextField TFusername;
    // End of variables declaration//GEN-END:variables
}
