package rentalmobil;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class KelolaMobil extends javax.swing.JFrame {

    /**
     * Creates new form KelolaMobil
     */
    
    public KelolaMobil() {
        initComponents();
        String username = UserSession.getUsername(); 
        UsernameLBL.setText(username.toUpperCase());
        setTitle("Aplikasi Rental Mobil");
        setLocationRelativeTo(null);
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLBL = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFidmobil = new javax.swing.JTextField();
        TFidtransaksi = new javax.swing.JTextField();
        TFidpeminjaman = new javax.swing.JTextField();
        KelolaMobil = new javax.swing.JLabel();
        BtnKelola = new javax.swing.JButton();
        BtnPeminjaman = new javax.swing.JButton();
        BtnTransaksi = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        BtnTambahAdmin = new javax.swing.JButton();
        BtnCek = new javax.swing.JButton();
        BtnKonfirmasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLBL.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        UsernameLBL.setForeground(new java.awt.Color(96, 197, 108));
        UsernameLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(UsernameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 180, 40));

        TFnama.setBorder(null);
        TFnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnamaActionPerformed(evt);
            }
        });
        getContentPane().add(TFnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 190, 30));

        TFidmobil.setBorder(null);
        getContentPane().add(TFidmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 190, 30));

        TFidtransaksi.setBorder(null);
        getContentPane().add(TFidtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 190, 30));

        TFidpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFidpeminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(TFidpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 190, 30));

        KelolaMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Kelola Mobil.png"))); // NOI18N
        KelolaMobil.setText("jLabel1");
        getContentPane().add(KelolaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        BtnKelola.setText("Kelola Mobil");
        BtnKelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKelolaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKelola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 160, 40));

        BtnPeminjaman.setText("Peminjaman");
        BtnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPeminjamanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 150, 50));

        BtnTransaksi.setText("Transaksi");
        BtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 40));

        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 150, 50));

        BtnTambahAdmin.setText("Tambah Admin");
        BtnTambahAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahAdminActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambahAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 230, 50));

        BtnCek.setText("Cek");
        BtnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCekActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, 190, 60));

        BtnKonfirmasi.setText("Konfirmasi");
        BtnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKonfirmasiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, 220, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKelolaActionPerformed
        // TODO add your handling code here:
        KelolaMobil km = new KelolaMobil();
        km.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKelolaActionPerformed

    private void BtnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPeminjamanActionPerformed
        // TODO add your handling code here:
        TabelPeminjaman pin = new TabelPeminjaman();
        pin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPeminjamanActionPerformed

    private void BtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaksiActionPerformed
        // TODO add your handling code here:
        TabelTransaksi tra = new TabelTransaksi();
        tra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTransaksiActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        HalamanAwal ha = new HalamanAwal();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void TFnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnamaActionPerformed

    private void BtnTambahAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahAdminActionPerformed
        // TODO add your handling code here:
        DaftarAdmin dad = new DaftarAdmin();
        dad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTambahAdminActionPerformed

    private void TFidpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFidpeminjamanActionPerformed
        // TODO add your handling code here:
        try {
        int IDpeminjam;
        IDpeminjam = Integer.parseInt(TFidpeminjaman.getText());
        }catch (NumberFormatException e) {
        // Menangani kasus jika input tidak valid (bukan angka)
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk ID.");
    }
    }//GEN-LAST:event_TFidpeminjamanActionPerformed

    private void BtnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCekActionPerformed
        // TODO add your handling code here:
        try {
        int IDpeminjam = Integer.parseInt(TFidpeminjaman.getText().trim());
        // Polymorphism: Memanggil proses pada CekData
        Proses cekData = new CekData(IDpeminjam, TFnama, TFidmobil, TFidtransaksi);
        cekData.proses();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk ID Peminjaman.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnCekActionPerformed

    private void BtnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKonfirmasiActionPerformed
        // TODO add your handling code here:
       try {
        int IDpeminjam = Integer.parseInt(TFidpeminjaman.getText().trim());
        // Polymorphism: Memanggil proses pada KonfirmasiData
        Proses konfirmasiData = new KonfirmasiData(IDpeminjam);
        konfirmasiData.proses();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk ID Peminjaman.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_BtnKonfirmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCek;
    private javax.swing.JButton BtnKelola;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnKonfirmasi;
    private javax.swing.JButton BtnPeminjaman;
    private javax.swing.JButton BtnTambahAdmin;
    private javax.swing.JButton BtnTransaksi;
    private javax.swing.JLabel KelolaMobil;
    private javax.swing.JTextField TFidmobil;
    private javax.swing.JTextField TFidpeminjaman;
    private javax.swing.JTextField TFidtransaksi;
    private javax.swing.JTextField TFnama;
    private javax.swing.JLabel UsernameLBL;
    // End of variables declaration//GEN-END:variables

    
}
