/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmobil;

/**
 *
 * @author Kevin
 */
public class MenuMobil extends javax.swing.JFrame {

    /**
     * Creates new form MenuMobil
     */
    public MenuMobil() {
        initComponents();
        String username = UserSession.getUsername();
        UsernameLBL.setText(username.toUpperCase());
        setTitle("Aplikasi Rental Mobil");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLBL = new javax.swing.JLabel();
        MenuMobil = new javax.swing.JLabel();
        BtnMobil = new javax.swing.JButton();
        BtnPembayaran = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLBL.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        UsernameLBL.setForeground(new java.awt.Color(96, 197, 108));
        UsernameLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(UsernameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 180, 40));

        MenuMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Menu Mobil.png"))); // NOI18N
        MenuMobil.setText("jLabel1");
        getContentPane().add(MenuMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        BtnMobil.setText("Mobil");
        BtnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMobilActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 170, 60));

        BtnPembayaran.setText("Pembayaran");
        BtnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 170, 60));

        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMobilActionPerformed
        // TODO add your handling code here:
        MenuMobil mbl = new MenuMobil();
        mbl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMobilActionPerformed

    private void BtnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPembayaranActionPerformed
        // TODO add your handling code here:
        Pembayaran pb = new Pembayaran();
        pb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPembayaranActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        HalamanAwal ha = new HalamanAwal();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnMobil;
    private javax.swing.JButton BtnPembayaran;
    private javax.swing.JLabel MenuMobil;
    private javax.swing.JLabel UsernameLBL;
    // End of variables declaration//GEN-END:variables
}
