/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmobil;

/**
 *
 * @author Kevin
 */
import javax.swing.*;
import java.sql.*;
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    String IdMobil;
    int Harga, JumlahUang, JumlahHari, Kembalian, TotalHarga;
    public Pembayaran() {
        initComponents();
        String username = UserSession.getUsername();
        UsernameLBL.setText(username.toUpperCase());
        setTitle("Aplikasi Rental Mobil");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLBL = new javax.swing.JLabel();
        Id_mobil = new javax.swing.JComboBox<>();
        TFjumlahhari = new javax.swing.JTextField();
        TFharga = new javax.swing.JTextField();
        TFjumlahuang = new javax.swing.JTextField();
        DP_Nama = new javax.swing.JTextField();
        DP_IdMobil = new javax.swing.JTextField();
        DP_JumlahHari = new javax.swing.JTextField();
        DP_Harga = new javax.swing.JTextField();
        DP_Kembalian = new javax.swing.JTextField();
        Pembayaran = new javax.swing.JLabel();
        BtnMobil = new javax.swing.JButton();
        BtnPembayaran = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        BtnHitung = new javax.swing.JButton();
        BtnBayar = new javax.swing.JButton();
        BtnSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLBL.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        UsernameLBL.setForeground(new java.awt.Color(96, 197, 108));
        UsernameLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(UsernameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 180, 40));

        Id_mobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih-", "H2024", "H2021", "K2021", "K2022", "M2020", "M2023" }));
        Id_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_mobilActionPerformed(evt);
            }
        });
        getContentPane().add(Id_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 150, -1));

        TFjumlahhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFjumlahhariActionPerformed(evt);
            }
        });
        getContentPane().add(TFjumlahhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 150, -1));

        TFharga.setBorder(null);
        TFharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhargaActionPerformed(evt);
            }
        });
        getContentPane().add(TFharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 150, -1));

        TFjumlahuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFjumlahuangActionPerformed(evt);
            }
        });
        getContentPane().add(TFjumlahuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 150, -1));

        DP_Nama.setBorder(null);
        getContentPane().add(DP_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 120, -1));

        DP_IdMobil.setBorder(null);
        getContentPane().add(DP_IdMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 100, -1));

        DP_JumlahHari.setBorder(null);
        getContentPane().add(DP_JumlahHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 110, 30));

        DP_Harga.setBorder(null);
        getContentPane().add(DP_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 100, -1));

        DP_Kembalian.setBorder(null);
        DP_Kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DP_KembalianActionPerformed(evt);
            }
        });
        getContentPane().add(DP_Kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 100, -1));

        Pembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Pembayaran.png"))); // NOI18N
        Pembayaran.setText("jLabel1");
        getContentPane().add(Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        BtnMobil.setText("Mobil");
        BtnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMobilActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 170, 60));

        BtnPembayaran.setText("Pembayaran");
        BtnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 170, 60));

        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 150, 50));

        BtnHitung.setText("Hitung");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 190, 50));

        BtnBayar.setText("Bayar");
        BtnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBayarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, 180, 50));

        BtnSelesai.setText("Selesai");
        BtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 610, 190, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMobilActionPerformed
        // TODO add your handling code here:
        MenuMobil mbl = new MenuMobil();
        mbl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMobilActionPerformed

    private void BtnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPembayaranActionPerformed
        // TODO add your handling code here:
        Pembayaran pb = new Pembayaran();
        pb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPembayaranActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        HalamanAwal ha = new HalamanAwal();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
        // TODO add your handling code here:
        try{
            JumlahHari = Integer.parseInt(TFjumlahhari.getText());
            TotalHarga = Harga * JumlahHari;
            TFharga.setText(String.valueOf(TotalHarga));
            }catch (NumberFormatException e) {
            // Menangani kesalahan jika jumlah hari tidak valid
            JOptionPane.showMessageDialog(this, "Masukkan jumlah hari yang valid.");
            }
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void BtnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBayarActionPerformed
        // TODO add your handling code here:
        try {
        String username = UserSession.getUsername();
        int jumlahHari = Integer.parseInt(TFjumlahhari.getText());
        int jumlahUang = Integer.parseInt(TFjumlahuang.getText());

        // Buat objek TransaksiPembayaran
        TransaksiPembayaran transaksi = new TransaksiPembayaran(IdMobil, Harga, jumlahHari, jumlahUang);

        // Proses pembayaran
        transaksi.prosesPembayaran(username);

        // Tampilkan informasi pembayaran
        DP_Nama.setText(username);
        DP_IdMobil.setText(IdMobil);
        DP_JumlahHari.setText(String.valueOf(jumlahHari));
        DP_Harga.setText(String.valueOf(transaksi.getTotalHarga()));
        DP_Kembalian.setText(String.valueOf(transaksi.getKembalian()));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan data yang valid.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_BtnBayarActionPerformed

    private void BtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelesaiActionPerformed
        // TODO add your handling code here:
        ThankYou ty = new ThankYou();
        ty.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSelesaiActionPerformed

    private void Id_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_mobilActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select * from mobil where ID_Mobil = '" + Id_mobil.getSelectedItem() + "'";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
            IdMobil = rs.getString("ID_Mobil");
            Harga = rs.getInt("Harga");
            }else {
            JOptionPane.showMessageDialog(this, "Mobil tidak ditemukan.");
            } 
        }catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Id_mobilActionPerformed

    private void TFjumlahhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFjumlahhariActionPerformed
        // TODO add your handling code here:
        try {
        // Mengambil teks dari JTextField dan mengonversinya menjadi Integer
        JumlahHari = Integer.parseInt(TFjumlahhari.getText());
        }catch (NumberFormatException e) {
        // Menangani kasus jika input tidak valid (bukan angka)
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk jumlah hari.");
    }
    }//GEN-LAST:event_TFjumlahhariActionPerformed

    private void TFjumlahuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFjumlahuangActionPerformed
        // TODO add your handling code here:
        try {
        // Mengambil teks dari JTextField dan mengonversinya menjadi Integer
        JumlahUang = Integer.parseInt(TFjumlahuang.getText());
        }catch (NumberFormatException e) {
        // Menangani kasus jika input tidak valid (bukan angka)
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk jumlah hari.");
        }
    }//GEN-LAST:event_TFjumlahuangActionPerformed

    private void TFhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhargaActionPerformed

    private void DP_KembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DP_KembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DP_KembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBayar;
    private javax.swing.JButton BtnHitung;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnMobil;
    private javax.swing.JButton BtnPembayaran;
    private javax.swing.JButton BtnSelesai;
    private javax.swing.JTextField DP_Harga;
    private javax.swing.JTextField DP_IdMobil;
    private javax.swing.JTextField DP_JumlahHari;
    private javax.swing.JTextField DP_Kembalian;
    private javax.swing.JTextField DP_Nama;
    private javax.swing.JComboBox<String> Id_mobil;
    private javax.swing.JLabel Pembayaran;
    private javax.swing.JTextField TFharga;
    private javax.swing.JTextField TFjumlahhari;
    private javax.swing.JTextField TFjumlahuang;
    private javax.swing.JLabel UsernameLBL;
    // End of variables declaration//GEN-END:variables
}
